name: Build & Publish Gradle Plugin

on:
  push:
    paths:
      - gradle-plugin/**
      - gradle.properties
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build
        run: ./gradlew :gradle-plugin:build
      - name: Publish
        run: ./gradlew :gradle-plugin:publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PLUGINS_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PLUGINS_SECRET }}
